import {createConstants} from '../utils/index';

export default createConstants(
    'GET_PERMISSIONS_REQUEST',
    'GET_PERMISSIONS_SUCCESS',
    'GET_PERMISSIONS_FAILURE',

    'GET_PERMISSION_REQUEST',
    'GET_PERMISSION_SUCCESS',
    'GET_PERMISSION_FAILURE',

    'DEL_PERMISSION_REQUEST',
    'DEL_PERMISSION_SUCCESS',
    'DEL_PERMISSION_FAILURE',

    'SAVE_PERMISSION_REQUEST',
    'SAVE_PERMISSION_SUCCESS',
    'SAVE_PERMISSION_FAILURE',

    'UPD_PERMISSION_REQUEST',
    'UPD_PERMISSION_SUCCESS',
    'UPD_PERMISSION_FAILURE',

    'CLEAR_PERMISSION',
    'ADD_PERMISSION',
    'PERMISSION_FIELD_VALUE',
    'CLEAR_PERMISSION_FIELD_VALUE'
);

